# SPDX-License-Identifier: MIT OR Apache-2.0
# SPDX-FileCopyrightText: Critical Section GmbH

---

name: CI
on:
  push:
    branches: [staging, trying]
  pull_request: {}

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Some Ferrocene builders require the use of Python 3.6. Use that on CI
      # to make sure there are no surprises when we import into Ferrocene.
      - uses: actions/setup-python@v3
        with:
          python-version: "3.6.x"

      - name: Build documentation
        run: ./make.py

      - name: Install REUSE
        run: python3 -m pip install reuse

      - name: Verify licensing metadata
        run: reuse lint

      - name: Publish to GitHub Pages
        uses: ferrous-systems/shared-github-actions/github-pages@main
        with:
          path: build/html
          token: ${{ secrets.GITHUB_TOKEN }}
        if: github.event_name == 'push' && github.ref == 'refs/heads/staging'
